// Beacon - seed data for demo mode (no backend required).
// Locations cluster around central London so the map & distance features feel real.
// Photos are intentionally null so the app renders its original pet illustrations.

import type { AlertArea, NotificationPrefs, PetReport } from './types';

const now = Date.now();
const hoursAgo = (h: number) => new Date(now - h * 3600_000).toISOString();
const daysAgo = (d: number) => new Date(now - d * 86_400_000).toISOString();

export const DEMO_USER = {
  id: 'demo-user',
  name: 'Alex Rivera',
  avatarUrl: null as string | null,
  email: 'alex@beacon.app',
};

export const demoReports: PetReport[] = [
  {
    id: 'r-biscuit',
    reporterId: 'n-sam',
    reporter: { id: 'n-sam', name: 'Sam Okafor' },
    kind: 'missing',
    status: 'active',
    name: 'Biscuit',
    species: 'dog',
    breed: 'Golden Retriever',
    colour: 'Golden',
    age: '3 years',
    size: 'large',
    description:
      'Super friendly, comes when called. Wearing a sky-blue collar with a bell. Slipped out of the garden gate during the storm.',
    photoUrl: null,
    lastSeenAt: hoursAgo(6),
    location: { lat: 51.5121, lng: -0.1235, label: 'Riverside Park, near the bandstand' },
    alertRadiusKm: 3,
    contactPref: 'in_app',
    createdAt: hoursAgo(6),
    updatedAt: hoursAgo(2),
    sightings: [
      {
        id: 's-1',
        reportId: 'r-biscuit',
        reporter: { id: 'n-mia', name: 'Mia' },
        seenAt: hoursAgo(3),
        location: { lat: 51.514, lng: -0.121, label: 'Corner of Elm Street' },
        photoUrl: null,
        notes: 'Saw a golden dog trotting toward the high street, looked a bit lost but happy.',
        createdAt: hoursAgo(3),
      },
    ],
  },
  {
    id: 'r-clementine',
    reporterId: 'n-priya',
    reporter: { id: 'n-priya', name: 'Priya Sharma' },
    kind: 'missing',
    status: 'active',
    name: 'Clementine',
    species: 'cat',
    breed: 'Tabby',
    colour: 'Orange and white',
    age: '2 years',
    size: 'small',
    description:
      'Shy but curious tabby. White chest and paws. Might be hiding under a car or in a shed. Responds to a shaken treat bag.',
    photoUrl: null,
    lastSeenAt: hoursAgo(20),
    location: { lat: 51.5039, lng: -0.1345, label: 'Maple Gardens' },
    alertRadiusKm: 1,
    contactPref: 'in_app',
    createdAt: hoursAgo(20),
    updatedAt: hoursAgo(20),
    sightings: [],
  },
  {
    id: 'r-pepper',
    reporterId: 'n-tom',
    reporter: { id: 'n-tom', name: 'Tom Bailey' },
    kind: 'missing',
    status: 'active',
    name: 'Pepper',
    species: 'dog',
    breed: 'Border Collie',
    colour: 'Black and white',
    age: '5 years',
    size: 'medium',
    description:
      'Energetic collie, a little nervous around traffic. Microchipped. Last seen chasing a squirrel near the allotments.',
    photoUrl: null,
    lastSeenAt: daysAgo(2),
    location: { lat: 51.5185, lng: -0.142, label: 'Greenwood Allotments' },
    alertRadiusKm: 5,
    contactPref: 'phone',
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
    sightings: [],
  },
  {
    id: 'r-luna',
    reporterId: 'n-jess',
    reporter: { id: 'n-jess', name: 'Jess Lin' },
    kind: 'missing',
    status: 'active',
    name: 'Luna',
    species: 'cat',
    breed: 'Domestic shorthair',
    colour: 'Black',
    age: '4 years',
    size: 'medium',
    description: 'All-black cat with bright yellow eyes and a small notch in her left ear.',
    photoUrl: null,
    lastSeenAt: hoursAgo(40),
    location: { lat: 51.4995, lng: -0.121, label: 'Station Road' },
    alertRadiusKm: 3,
    contactPref: 'in_app',
    createdAt: hoursAgo(40),
    updatedAt: hoursAgo(40),
    sightings: [],
  },
  {
    id: 'r-nibbles',
    reporterId: 'n-omar',
    reporter: { id: 'n-omar', name: 'Omar Haddad' },
    kind: 'missing',
    status: 'active',
    name: 'Nibbles',
    species: 'other',
    breed: 'Holland Lop rabbit',
    colour: 'Grey',
    age: '1 year',
    size: 'small',
    description: 'Escaped from the garden hutch. Floppy ears, very gentle. Loves dandelion leaves.',
    photoUrl: null,
    lastSeenAt: hoursAgo(30),
    location: { lat: 51.5075, lng: -0.128, label: 'Chestnut Close' },
    alertRadiusKm: 1,
    contactPref: 'in_app',
    createdAt: hoursAgo(30),
    updatedAt: hoursAgo(30),
    sightings: [],
  },
  {
    id: 'r-found-collie',
    reporterId: 'n-grace',
    reporter: { id: 'n-grace', name: 'Grace Miller' },
    kind: 'found',
    status: 'active',
    name: null,
    species: 'dog',
    breed: 'Looks like a Border Collie',
    colour: 'Black and white',
    age: 'Adult',
    size: 'medium',
    description: 'Found a friendly black-and-white dog, no collar. Currently safe in my kitchen.',
    photoUrl: null,
    lastSeenAt: hoursAgo(4),
    location: { lat: 51.517, lng: -0.139, label: 'Near Greenwood Allotments' },
    stillHasPet: true,
    notes: 'Very well behaved, seems house-trained. Happy to hold onto them until the owner is found.',
    contactPref: 'in_app',
    createdAt: hoursAgo(4),
    updatedAt: hoursAgo(4),
    sightings: [],
  },
  {
    id: 'r-reunited-milo',
    reporterId: 'n-dev',
    reporter: { id: 'n-dev', name: 'Dev Patel' },
    kind: 'missing',
    status: 'reunited',
    name: 'Milo',
    species: 'cat',
    breed: 'Ragdoll',
    colour: 'Cream and grey',
    age: '6 years',
    size: 'medium',
    description: 'Fluffy ragdoll with blue eyes. Home safe thanks to a neighbour two streets over!',
    photoUrl: null,
    lastSeenAt: daysAgo(5),
    location: { lat: 51.506, lng: -0.132, label: 'Willow Terrace' },
    alertRadiusKm: 3,
    contactPref: 'in_app',
    createdAt: daysAgo(5),
    updatedAt: daysAgo(3),
    reunitedAt: daysAgo(3),
    sightings: [],
  },
  {
    id: 'r-reunited-rex',
    reporterId: 'n-ana',
    reporter: { id: 'n-ana', name: 'Ana Costa' },
    kind: 'missing',
    status: 'reunited',
    name: 'Rex',
    species: 'dog',
    breed: 'Beagle',
    colour: 'Tricolour',
    age: '2 years',
    size: 'small',
    description: 'Cheeky beagle who followed his nose too far. Reunited after a sighting at the park!',
    photoUrl: null,
    lastSeenAt: daysAgo(8),
    location: { lat: 51.51, lng: -0.12, label: 'Riverside Park' },
    alertRadiusKm: 5,
    contactPref: 'in_app',
    createdAt: daysAgo(8),
    updatedAt: daysAgo(6),
    reunitedAt: daysAgo(6),
    sightings: [],
  },
];

export const demoAreas: AlertArea[] = [
  {
    id: 'a-home',
    userId: DEMO_USER.id,
    label: 'Home',
    lat: 51.5074,
    lng: -0.1278,
    radiusKm: 3,
    speciesFilter: 'all',
    isActive: true,
    createdAt: daysAgo(30),
  },
  {
    id: 'a-work',
    userId: DEMO_USER.id,
    label: 'Work',
    lat: 51.5155,
    lng: -0.1419,
    radiusKm: 1,
    speciesFilter: 'dogs',
    isActive: true,
    createdAt: daysAgo(20),
  },
];

export const demoPrefs: NotificationPrefs = {
  userId: DEMO_USER.id,
  alertsEnabled: false,
  defaultRadiusKm: 3,
  speciesFilter: 'all',
};
